
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  password: 1302
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development

 
test:
  <<: *default
  database: backend_test


production:
  <<: *default
  database: backend_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
